### ISSUE TITLE
Cmake error: install TARGETS given no RUNTIME DESTINATION

### ISSUE THREAD

**Issue by grumble9684** [chmod222/libcmmk#20]
So I copy all the commands from the README and this is what cmake says after 
cmake -DCMAKE_INSTALL_PREFIX=dist ..

**CMake Error at test/CMakeLists.txt:21 (install):
  install TARGETS given no RUNTIME DESTINATION for executable target
  "cmmk-test".**

Seems to be an issue with CMakeLists.txt

**Comment by sam97** [comment]
I’m not well versed in this project, but it seems that the `CMAKE_INSTALL_BINDIR` may not be set. Can you try running cmake with `--trace-expand-` to confirm this?

If that is the case then maybe adding `include(GNUInstallDirs)` before line 21 in tests/CMakeLists.txt may help.
